commit

diff --git a/7.1/apache/jessie/Dockerfile b/7.1/apache/jessie/Dockerfile
--- a/7.1/apache/jessie/Dockerfile
+++ b/7.1/apache/jessie/Dockerfile
@@ -1,8 +1,6 @@
-ARG TAG
+FROM php:7.1-apache-jessie
+MAINTAINER Brett Tasker '<brett@silverstripe.com>'
 
-FROM php:$TAG
-MAINTAINER Brett Tasker "<brett@silverstripe.com>"
-ENV DEBIAN_FRONTEND=noninteractive
 COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/install-php-extensions
 
 # Install default PHP Extensions
@@ -19,31 +17,49 @@ RUN install-php-extensions \
         xsl \
         zip \
         exif \
-        gmp
+        gmp \
+        opcache
 
-# Pipe errors to stdErr
-RUN echo "date.timezone = Pacific/Auckland" > /usr/local/etc/php/conf.d/timezone.ini && \
-    echo "log_errors = On\nerror_log = /dev/stderr" > /usr/local/etc/php/conf.d/errors.ini
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+	docker-php-ext-enable opcache; \
+	{ \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+
+# Set error handling
+RUN echo 'date.timezone = Pacific/Auckland' > /usr/local/etc/php/conf.d/timezone.ini && \ 
+    { \
+        echo 'log_errors = On'; \
+        echo 'error_log = /dev/stderr'; \
+    } > /usr/local/etc/php/conf.d/errors.ini
+
+
 # Apache configuration
 ENV DOCUMENT_ROOT /var/www/html
 RUN { \
-                echo '<VirtualHost *:80>'; \
-                echo '  DocumentRoot ${DOCUMENT_ROOT}'; \
-                echo '  LogLevel warn'; \
-                echo '  ServerSignature Off'; \
-                echo '  <Directory ${ENVVAR}>'; \
-                echo '    Options +FollowSymLinks'; \
-                echo '    Options -ExecCGI -Includes -Indexes'; \
-                echo '    AllowOverride all'; \
-                echo; \
-                echo '    Require all granted'; \
-                echo '  </Directory>'; \
-                echo '  <LocationMatch assets/>'; \
-                echo '    php_flag engine off'; \
-                echo '  </LocationMatch>'; \
-                echo; \
-                echo '  IncludeOptional sites-available/000-default.local*'; \
-                echo '</VirtualHost>'; \
-	} | tee /etc/apache2/sites-available/000-default.conf && \
+        echo '<VirtualHost *:80>'; \
+        echo '  DocumentRoot ${DOCUMENT_ROOT}'; \
+        echo '  LogLevel warn'; \
+        echo '  ServerSignature Off'; \
+        echo '  <Directory ${ENVVAR}>'; \
+        echo '    Options +FollowSymLinks'; \
+        echo '    Options -ExecCGI -Includes -Indexes'; \
+        echo '    AllowOverride all'; \
+        echo; \
+        echo '    Require all granted'; \
+        echo '  </Directory>'; \
+        echo '  <LocationMatch assets/>'; \
+        echo '    php_flag engine off'; \
+        echo '  </LocationMatch>'; \
+        echo; \
+        echo '  IncludeOptional sites-available/000-default.local*'; \
+        echo '</VirtualHost>'; \
+	} > /etc/apache2/sites-available/000-default.conf && \
     echo "ServerName localhost" > /etc/apache2/conf-available/fqdn.conf && \
-    a2enmod rewrite expires remoteip cgid headers
+    a2enmod rewrite expires remoteip headers
diff --git a/7.3/fpm/stretch/Dockerfile b/7.3/fpm/stretch/Dockerfile
--- a/7.3/fpm/stretch/Dockerfile
+++ b/7.3/fpm/stretch/Dockerfile
@@ -1,8 +1,6 @@
-ARG TAG
+FROM php:7.3-fpm-stretch
+MAINTAINER Brett Tasker '<brett@silverstripe.com>'
 
-FROM php:$TAG
-MAINTAINER Brett Tasker "<brett@silverstripe.com>"
-ENV DEBIAN_FRONTEND=noninteractive
 COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/install-php-extensions
 
 # Install default PHP Extensions
@@ -19,8 +17,25 @@ RUN install-php-extensions \
         xsl \
         zip \
         exif \
-        gmp
+        gmp \
+        opcache
 
-# Pipe errors to stdErr
-RUN echo "date.timezone = Pacific/Auckland" > /usr/local/etc/php/conf.d/timezone.ini && \
-    echo "log_errors = On\nerror_log = /dev/stderr" > /usr/local/etc/php/conf.d/errors.ini
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+	docker-php-ext-enable opcache; \
+	{ \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+
+# Set error handling
+RUN echo 'date.timezone = Pacific/Auckland' > /usr/local/etc/php/conf.d/timezone.ini && \ 
+    { \
+        echo 'log_errors = On'; \
+        echo 'error_log = /dev/stderr'; \
+    } > /usr/local/etc/php/conf.d/errors.ini
+
